name: GitHub Pages

on:
  push:
    branches:
      - master # Set a branch name to trigger deployment
jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0
          ssh-key: ${{ secrets.TOKENIZED_EUROS_DEPLOY_KEY }}

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          publish_dir: ./docs
